{{- if .Values.isolateComponents }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "seleniumGrid.sessionQueue.configmap.fullname" $ }}
  namespace: {{ .Release.Namespace }}
{{- with .Values.sessionQueueConfigMap.annotations }}
  annotations: {{- toYaml . | nindent 4 }}
{{- end }}
  labels:
    {{- include "seleniumGrid.commonLabels" . | nindent 4 }}
    {{- with .Values.customLabels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
data:
  SE_SESSION_QUEUE_HOST: '{{ template "seleniumGrid.sessionQueue.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local'
  SE_SESSION_QUEUE_PORT: '{{ .Values.components.sessionQueue.port }}'
{{- end }}
