#!/bin/bash
set -e

if [ "$(id -u)" == 0 ]; then
    # For root user to change ownership
    for d in "$@"; do
        find "${d}" \
            ! \( \
                -group "${SEL_GID}" \
                -a -perm -g+rwX \
            \) \
            -exec chown -R "${SEL_USER}:${SEL_GID}" -- {} \+ \
            -exec chgrp -R "${SEL_GID}" -- {} \+ \
            -exec chmod -R g+rwX -- {} \+
        # setuid, setgid *on directories only*
        find "${d}" \
            \( \
                -type d \
                -a ! -perm -6000 \
            \) \
            -exec chmod -R +6000 -- {} \+
        # Relaxing permissions for OpenShift and other non-sudo environments
        chmod -R u+x "${d}"
        chgrp -R ${CHGRP_EXTRA:-0} "${d}"
        chmod -R g=u "${d}"
    done
fi
