name: Test Helm Charts Set Component OverrideName

on:
  workflow_dispatch:
  push:
    paths:
      - 'charts/selenium-grid/templates/*'
  pull_request:
    paths:
      - 'charts/selenium-grid/templates/*'

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.13.2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10
          check-latest: true

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.6.1

      - name: Build chart dependencies
        run: |
          helm repo add kedacore https://kedacore.github.io/charts
          helm repo update
          helm dependency build charts/selenium-grid

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --target-branch ${{ github.event.repository.default_branch }})
          if [[ -n "$changed" ]]; then
            echo "changed=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Create kind cluster
        uses: helm/kind-action@v1.8.0

      - name: Run chart-testing (install)
        run: ct install --config tests/ChartTests/ct-nameOverride.yaml --target-branch ${{ github.event.repository.default_branch }}
